version: '3'
services:
    cef-container:
        build:
            context: .
        container_name: cef-container
        ports:
            - 5000:22
        volumes:
            - ../../:/workspace:cached
        deploy:
            resources:
                reservations:
                    memory: 1024M
                limits:
                    memory: 4000M
        environment:
            - QT_X11_NO_MITSHM=1
            - _X11_NO_MITSHM=1
            - _MITSHM=0
        ipc: host
        #command: /bin/bash -c "cd /workspace && while true; do sleep 3600; done"